// <auto-generated />
using JW.Alarm.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JW.Alarm.Services.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20190208045643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("JW.Alarm.Models.AlarmMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlarmScheduleId");

                    b.Property<bool>("Fixed");

                    b.Property<string>("LanguageCode");

                    b.Property<int>("MusicType");

                    b.Property<string>("PublicationCode");

                    b.Property<int>("TrackNumber");

                    b.HasKey("Id");

                    b.HasIndex("AlarmScheduleId")
                        .IsUnique();

                    b.ToTable("AlarmMusic");
                });

            modelBuilder.Entity("JW.Alarm.Models.AlarmSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentPlayItem");

                    b.Property<int>("DaysOfWeek");

                    b.Property<int>("Hour");

                    b.Property<bool>("IsEnabled");

                    b.Property<int>("Minute");

                    b.Property<bool>("MusicEnabled");

                    b.Property<string>("Name");

                    b.Property<int>("Second");

                    b.Property<int>("SnoozeMinutes");

                    b.HasKey("Id");

                    b.ToTable("AlarmSchedules");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleReadingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlarmScheduleId");

                    b.Property<int>("BookNumber");

                    b.Property<int>("ChapterNumber");

                    b.Property<string>("LanguageCode");

                    b.Property<string>("PublicationCode");

                    b.HasKey("Id");

                    b.HasIndex("AlarmScheduleId")
                        .IsUnique();

                    b.ToTable("BibleReadingSchedule");
                });

            modelBuilder.Entity("JW.Alarm.Models.AlarmMusic", b =>
                {
                    b.HasOne("JW.Alarm.Models.AlarmSchedule", "AlarmSchedule")
                        .WithOne("Music")
                        .HasForeignKey("JW.Alarm.Models.AlarmMusic", "AlarmScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleReadingSchedule", b =>
                {
                    b.HasOne("JW.Alarm.Models.AlarmSchedule", "AlarmSchedule")
                        .WithOne("BibleReadingSchedule")
                        .HasForeignKey("JW.Alarm.Models.BibleReadingSchedule", "AlarmScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
