// <auto-generated />
using System;
using JW.Alarm.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bible.Alarm.Services.Infrastructure.Media.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20190209043606_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("JW.Alarm.Models.BibleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BibleTranslationId");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.HasIndex("BibleTranslationId");

                    b.ToTable("BibleBook");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BibleBookId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("Number");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.ToTable("BibleChapter");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("LanguageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("BibleTranslations");
                });

            modelBuilder.Entity("JW.Alarm.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("JW.Alarm.Models.MusicTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("Number");

                    b.Property<int>("SongBookId");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("SongBookId");

                    b.ToTable("MusicTrack");
                });

            modelBuilder.Entity("JW.Alarm.Models.SongBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("LanguageId");

                    b.Property<int>("MusicType");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("SongBooks");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleBook", b =>
                {
                    b.HasOne("JW.Alarm.Models.BibleTranslation", "BibleTranslation")
                        .WithMany("Books")
                        .HasForeignKey("BibleTranslationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleChapter", b =>
                {
                    b.HasOne("JW.Alarm.Models.BibleBook", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleTranslation", b =>
                {
                    b.HasOne("JW.Alarm.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.MusicTrack", b =>
                {
                    b.HasOne("JW.Alarm.Models.SongBook", "SongBook")
                        .WithMany("Tracks")
                        .HasForeignKey("SongBookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.SongBook", b =>
                {
                    b.HasOne("JW.Alarm.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
