// <auto-generated />
using System;
using JW.Alarm.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bible.Alarm.Services.Infrastructure.Media.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("JW.Alarm.Models.AudioSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("AudioSource");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BibleTranslationId");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.HasIndex("BibleTranslationId");

                    b.ToTable("BibleBook");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BibleBookId");

                    b.Property<int>("Number");

                    b.Property<int?>("SourceId");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.HasIndex("SourceId");

                    b.ToTable("BibleChapter");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("DisplayLanguageId");

                    b.Property<int>("LanguageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("BibleTranslations");
                });

            modelBuilder.Entity("JW.Alarm.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("JW.Alarm.Models.MelodyMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("DisplayLanguageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.ToTable("MelodyMusic");
                });

            modelBuilder.Entity("JW.Alarm.Models.MusicTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MelodyMusicId");

                    b.Property<int>("Number");

                    b.Property<int?>("SourceId");

                    b.Property<string>("Title");

                    b.Property<int?>("VocalMusicId");

                    b.HasKey("Id");

                    b.HasIndex("MelodyMusicId");

                    b.HasIndex("SourceId");

                    b.HasIndex("VocalMusicId");

                    b.ToTable("MusicTrack");
                });

            modelBuilder.Entity("JW.Alarm.Models.VocalMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("DisplayLanguageId");

                    b.Property<int>("LanguageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("VocalMusic");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleBook", b =>
                {
                    b.HasOne("JW.Alarm.Models.BibleTranslation", "BibleTranslation")
                        .WithMany("Books")
                        .HasForeignKey("BibleTranslationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleChapter", b =>
                {
                    b.HasOne("JW.Alarm.Models.BibleBook", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JW.Alarm.Models.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("JW.Alarm.Models.BibleTranslation", b =>
                {
                    b.HasOne("JW.Alarm.Models.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JW.Alarm.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.MelodyMusic", b =>
                {
                    b.HasOne("JW.Alarm.Models.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JW.Alarm.Models.MusicTrack", b =>
                {
                    b.HasOne("JW.Alarm.Models.MelodyMusic")
                        .WithMany("Tracks")
                        .HasForeignKey("MelodyMusicId");

                    b.HasOne("JW.Alarm.Models.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("JW.Alarm.Models.VocalMusic")
                        .WithMany("Tracks")
                        .HasForeignKey("VocalMusicId");
                });

            modelBuilder.Entity("JW.Alarm.Models.VocalMusic", b =>
                {
                    b.HasOne("JW.Alarm.Models.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JW.Alarm.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
