name: Update media links

on:
  schedule:
    - cron:  '0 2 * * *'
    
jobs:
  build:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Run Link Harvestor
      run: dotnet run --project src/_tools/Bible.Alarm.Audio.Links.Harvestor/Bible.Alarm.Audio.Links.Harvestor.csproj --configuration Release
     
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
          author_name: buildbot171
          author_email: buildbot171@gmail.com
          message: 'Update media links database'
          add: '*.zip'
